urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^offer/create/$',              views.OfferCreateView.as_view(),   name='offer_create'),
    url(r'^demand/create/$',             views.DemandCreateView.as_view(),  name='demand_create'),
    url(r'^detail/(?P<pk>\d+)/$',        views.OfferDetailView.as_view(),   name='detail'),
    url(r'^offer/update/(?P<pk>\d+)/$',  views.OfferUpdateView.as_view(),   name='offer_update'),
    url(r'^demand/update/(?P<pk>\d+)/$', views.DemandUpdateView.as_view(),  name='demand_update'),
    url(r'^delete/(?P<pk>\d+)/$',        views.OfferDeleteView.as_view(),   name='delete'),
    url(r'^renew/(?P<pk>\d+)/$',         views.OfferRenewView.as_view(),    name='renew'),

    url(r'^$',                           views.OfferListView.as_view(),),
    url(r'^offer/$',                     views.OfferListView.as_view(),     name='offer_list'),
    url(r'^demand/$',                    views.DemandListView.as_view(),    name='demand_list'),
)

forms.py
# coding: utf-8

from django import forms
from django.forms.models import inlineformset_factory
from django.utils.translation import ugettext_lazy as _

from selectable.forms.widgets import AutoComboboxSelectWidget

from deal.models.cargos import City, MoneyType
from deal.helpers.lookups import CityLookup

from .models import Offer, Photo, Goods, Country, MoneyType, Payment

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        
    def __init__(self, *args, **kwargs):
        super(PhotoForm, self).__init__(*args, **kwargs)

        self.fields['img'].label = ''
        self.fields['img'].widget = forms.FileInput()

OfferPhotoInline = inlineformset_factory(Offer, Photo, fields=('img',), can_delete=False, extra=4, max_num=4, form=PhotoForm)

class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)

        self.fields['goods'].empty_label = _(u'Выберите тип товара..')
        self.fields['origin_country'].empty_label = _(u'Выберите страну происхождения..')
        self.fields['country'].empty_label = _(u'Выберите страну..')
        self.fields['region'].empty_label = _(u'Выберите регион..')
        self.fields['region'].queryset = City.objects.filter(flag=2, country_code=u'ru').all()
        try: self.initial['money_type'] = MoneyType.objects.get(title='RUB').id
        except: pass
        self.fields['money_type'].empty_label = None

    def clean(self):
        cleaned_data = super(BaseForm, self).clean()

        country = self.cleaned_data.get('country')
        region = self.cleaned_data.get('region')
        if country and country.id == 3159 and not region:
            self._errors['region'] = self.error_class(forms.ValidationError(self.fields['region'].error_messages['required']).messages)

        return cleaned_data

    class Meta:
        model = Offer
        widgets = {   
            'offer_type': forms.RadioSelect(attrs={'id':'offer_type', 'class':'offer_type'}),
            'goods': forms.Select(attrs={'class':'select small long'}),
            'grade': forms.TextInput(attrs={'class':'text small long', 'placeholder':_(u'Укажите сорт..')}),
            'caliber_min': forms.TextInput(attrs={'class': 'small select middle text fr', 'placeholder':_(u'От..')}),
            'caliber_max': forms.TextInput(attrs={'class': 'small select middle text fr', 'placeholder':_(u'До..')}),
            'manufacturer': forms.TextInput(attrs={'class':'text small long', 'placeholder':_(u'Укажите производителя..')}),
            'origin_country': forms.Select(attrs={'class': 'select small long'}),
            'pack': forms.TextInput( attrs={'class':'small text long', 'placeholder':_(u'Укажите вид упаковки..')}),
            'country': forms.Select(attrs={'class': 'select small long'}),
            'region': forms.Select(attrs={'class': 'select small long'}),
            'location': AutoComboboxSelectWidget(lookup_class=CityLookup, attrs={'class':'text small long', 'placeholder': _(u'Введите город..')}),
            'delivery': forms.CheckboxInput(),
            'price': forms.widgets.TextInput(attrs={'class':'text small middle fr', 'placeholder': _(u'Укажите стоимость..')}),
            'money_type': forms.widgets.Select(attrs={'class':'small select short fr'}),
            'payment_type': forms.CheckboxSelectMultiple(),
            'notes': forms.widgets.Textarea(attrs={'class':'textarea small long', 'rows':8, 'placeholder':_(u'Укажите дополнительные сведения при необходимости')}),
            'user': forms.widgets.HiddenInput(),
            'company': forms.widgets.HiddenInput(),
        }

class OfferCreateForm(BaseForm):
    class Meta(BaseForm.Meta):
        fields = (
            'offer_type',
            'goods','grade','caliber_min','caliber_max','manufacturer','origin_country',
            'pack','country','region','location',
            'price','money_type','payment_type',
            'notes',
        )

    def __init__(self, *args, **kwargs):
        super(OfferCreateForm, self).__init__(*args, **kwargs)

        self.initial['offer_type'] = 1


class DemandCreateForm(BaseForm):
    class Meta(BaseForm.Meta):
        fields = (
            'offer_type',
            'goods','grade','caliber_min','caliber_max','origin_country',
            'pack','country','region','location','delivery',
            'price','money_type','payment_type',
            'notes',
        )

    def __init__(self, *args, **kwargs):
        super(DemandCreateForm, self).__init__(*args, **kwargs)

        self.initial['offer_type'] = 0

        self.fields['notes'].label = _(u'Примечание')
        self.fields['country'].label = _(u'Мое местонахождение')

class BaseSearchForm(forms.Form):
    # Нужно, чтобы определить, заполнялась ли форма, или дергались переключатели вне ее
    #  страницы в пагинаторе или фильтр "мои/партнеров и т.д."
    # Все данные текстовые, т.к. сверяем с еще не почищеными данными из GET
    initial = {
        'goods': '',
        'caliber_min': '',
        'caliber_max': '',
        'origin_country': '',
        'price_min': '',
        'price_max': '',
        'money_type': '1',
        'payment_type': '',
        'country': '',
        'region': '',
        'location': '',
        'delivery': '2',
    }

    offer_view_filter = forms.CharField(widget=forms.HiddenInput(), required=False)
    offer_type = forms.CharField(widget=forms.HiddenInput(), required=False)
    goods = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'select small long'}), label=Offer.goods.field.verbose_name, empty_label=_(u'Любое'), queryset=Goods.objects.all(), required=False)
    caliber_min = forms.CharField(label=Offer._meta.get_field('caliber_min').verbose_name, widget=forms.TextInput(attrs={'class': 'small select middle text fr', 'placeholder':_(u'От..')}), required=False)
    caliber_max = forms.CharField(label=Offer._meta.get_field('caliber_max').verbose_name, widget=forms.TextInput(attrs={'class': 'small select middle text fr', 'placeholder':_(u'До..')}), required=False)
    origin_country = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'select small long'}), label=Offer.origin_country.field.verbose_name, empty_label=_(u'Любая'), queryset=Country.objects.all(), required=False)
    price_min = forms.DecimalField(label=_(u'Цена, за кг'), widget=forms.TextInput(attrs={'class': 'small short text fr', 'placeholder':_(u'От..')}), required=False)
    price_max = forms.DecimalField(widget=forms.TextInput(attrs={'class': 'small short text fr', 'placeholder':_(u'До..')}), required=False)
    money_type = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'small select short short2 fr'}), empty_label=_(u'Любая'), label=Offer.money_type.field.verbose_name, queryset=MoneyType.objects.all(), required=False)
    payment_type = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), label=Offer.payment_type.field.verbose_name, queryset=Payment.objects.all(), required=False)
    country = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'select small long'}), label=Offer.country.field.verbose_name, empty_label=_(u'Любая страна'), queryset=Country.objects.all(), required=False)
    region  = forms.ModelChoiceField(widget=forms.Select(attrs={'class':'select small long'}), label=Offer.region.field.verbose_name, empty_label=_(u'Любой регион'), queryset = City.objects.filter(flag=2, country_code=u'ru').all(), required=False)
    location = forms.ModelChoiceField(widget=AutoComboboxSelectWidget(lookup_class=CityLookup, attrs={'class':'text small long', 'placeholder': _(u'Любой город')}), queryset=City.objects.all(), required=False)
    delivery = forms.NullBooleanField(required=False, widget=forms.widgets.RadioSelect(choices=[(1, _(u'Да')), (0, _(u'Нет')), (2, _(u'Неважно'))]), initial=2)

    def __init__(self, *args, **kwargs):
        super(BaseSearchForm, self).__init__(*args, **kwargs)

        try: self.initial['money_type'] = MoneyType.objects.get(title='RUB').id 
        except: pass
        self.fields['delivery'].label = _(u'Нужна доставка')

class OfferSearchForm(BaseSearchForm):
    def __init__(self, *args, **kwargs):
        super(OfferSearchForm, self).__init__(*args, **kwargs)

        self.initial['offer_type'] = 1

class DemandSearchForm(BaseSearchForm):

    def __init__(self, *args, **kwargs):
        super(DemandSearchForm, self).__init__(*args, **kwargs)

        self.initial['offer_type'] = 0

templates/market/_buttons.html
{% load i18n %}
{% load deal_patterns %}
<div class="left_column4">
    {% if item.company != request.user.employee.company %}
        <a href="/deals/create/" class="button green fl"><span>{% trans "Создать сделку" %}</span></a>
        {% if item.notes %}
        <a href="" id="dbutton{{ item.id }}" class="button fl" onClick="toggle_notes({{ item.id }},'{% trans "Подробнее" %}','{% trans "Скрыть" %}'); return false;"><span>{% trans "Подробнее" %}</span></a>
        {% endif %}
        {% if user.is_authenticated %}
        <a href="/messages/asc_answer/offer/{{ item.id }}/{{ item.company.id }}/" class="button fr mess_asc_answer"><span>{{ trans_question_ask }}</span></a>
        {% endif %}
    {% else %}              
        <a href="{% if item.offer_type %}{% url market:offer_update item.id %}{% else %}{% url market:demand_update item.id %}{% endif %}" class="button green fl"><span>{% trans "Редактировать" %}</span></a>
        {% if item.notes %}
        <a href="" id="dbutton{{ item.id }}" class="button fl" onClick="toggle_notes({{ item.id }},'{% trans "Подробнее" %}','{% trans "Скрыть" %}'); return false;"><span>{% trans "Подробнее" %}</span></a>
        {% endif %}
        {% if item.date_create|days_ago > 0 %}
            <a href="{% url market:renew item.id %}" class="button fr"><span>{% trans "Обновить" %}</span></a>
        {% endif %}
        <a href="" onClick="delete_offer_ajax('{% url market:delete item.id %}', '{{ csrf_token }}', '{% if 'detail' in request.get_full_path %}{% if item.offer_type %}{% url market:offer_list %}{% else %}{% url market:demand_list %}{%endif%}{% endif %}'); return false;" class="button fr"><span>{% trans "Удалить" %}</span></a>
    {% endif %}
</div>
<div class="right_column4">
    <div class="option">
        <a href="/offer/{{ item.id }}/">
        <div class="date">
            {{ item.date_create|timesince }} {% trans "назад" %}
        </div>
        </a>
    </div>
</div>
<div class="forward_form ask_question block_border" style="display: none;"></div>

templates/market/_offer.html
{% load i18n %}
<div class="block_border none_border {% if forloop.last %} none_margin_bottom {% endif %}" id="offer_short{{ item.id }}">
    <div class="two_columns block_border search_result" id="market{{item.id}}">
        <div class="left_column2 search_result">
            <a href="{% url market:detail item.id %}"><img class="small" src="{{ item.image_url|default_if_none:"/static/market/nophoto.png" }}" /></a>
        </div>
        <div class="right_column market">
           {% include "market/_status.html" %}
    
            <div class="two_columns no_padding">
                <br/>
                <div class="one_column11 market">
                    <div class="info_line"><span class="title">{% trans "Сорт" %}:</span><span class="info">{{ item.grade }}</span></div>
                    <div class="info_line"><span class="title">{% trans "Цена" %}:</span><span class="info">{{ item.price|floatformat:"0" }} {{ item.money_type }}&nbsp;/&nbsp;{% trans "КГ" %}</span></div>
                    <div class="info_line"><span class="title">{% trans "Упаковка" %}:</span><span class="info">{{ item.pack }}</span></div>
                    {% if not item.offer_type %}
                    <div class="info_line"><span class="title">{% trans "Страна&nbsp;пр." %}:</span><span class="info">{% if item.origin_country %}{{ item.origin_country }}{% endif %}</span></div>
                    {% else %}
                    <div class="info_line"><span class="title">{% trans "Производитель" %}:</span><span class="info">{% if item.manufacturer %}{{ item.manufacturer }}{% endif %}</span></div>
                    {% endif %}
                </div>
                <div class="one_column12 market">
                    <div class="info_line"><span class="title">{% trans "Калибр" %}:</span><span class="info">{% if item.caliber_min and item.caliber_max%}{{ item.caliber_min }} - {{ item.caliber_max }}{% endif %}</span></div>
                    <div class="info_line"><span class="title">{% trans "Оплата" %}:</span><span class="info">{{ item.payments }}</span></div>
                    {% if not item.offer_type %}
                    <div class="info_line"><span class="title">{% trans "Нужна доставка" %}:</span><span class="info">{% if item.delivery %}{% trans "Да" %}{% else %}{% trans "Нет" %}{% endif %}</span></div>
                    {% endif %}
                    {% if not item.offer_type %}
                    <div class="info_line"><span class="title">{% trans "Я&nbsp;нахожусь" %}:</span><span class="info">{{ item.location }}</span></div>
                    {% else %}
                    <div class="info_line"><span class="title">{% trans "Место&nbsp;груза" %}:</span><span class="info">{{ item.location }}</span></div>
                    {% endif %}
                </div>
            </div>
            <div class="clear"></div>
        </div>
        {% if item.notes %}
        <div class="line_gray no_padding" id="line{{ item.id }}" style="display: none;"></div>
        <div class="right_column market" id="notes{{ item.id }}" style="display: none;">
          <div class="info_line"><span class="info no_padding">{{ item.notes|safe }}</span></div>
        </div>
        {% endif %}
    </div>
    <div class="gray_block market">
      {% include "market/_buttons.html" %}
    </div>
    <div class="clear"></div>
</div>

templates/market/_pagination.html
{% if is_paginated %}
{% load i18n %}
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="prev">&lsaquo;&lsaquo; {% trans "Пред." %}</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "Пред." %}</span>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?page={{ page }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
        <span style="float:left;padding-left: 10px;padding-right: 5px;">...</span>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="next">{% trans "След." %} &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">{% trans "След." %} &rsaquo;&rsaquo;</span>
    {% endif %}
</div>
{% endif %}

templates/market/_status.html
{% load i18n %}
{% load deal_patterns %}
<div class="status_block search_result">
    <div class="tab name">
        <a href="{% url market:detail item.id %}">{{ item.goods }}</a>
    </div>
    <div class="tab rating_yellow">
        {% load rating from deal_patterns %}
        <div class="rateit" data-rateit-value="{{ item.company|rating }}"  data-rateit-min="0" data-rateit-max="5" data-rateit-step="0.25"  data-rateit-ispreset="true" data-rateit-readonly="true"></div>
    </div>
    <div class="tab flag">
        <div class="yellow_left">
            <a href="{{ item.user.employee.company|get_profile_url }}">{{ item.user.employee.company }}</a>
        </div>
        <div class="yellow_right"></div>
    </div>
    {% if user.is_authenticated %}
        {% if item.company == request.user.employee.company or item.is_partner %}
    <div class="tab next">
        {% if item.company == request.user.employee.company %}
        <div>{% if item.offer_type %}{% trans "мое предложение" %}{% else %}{% trans "мой спрос" %}{% endif %}</div>
        {% endif %}

        {% if user.is_authenticated %}
            {% if item.is_partner %}
            <div>{% if item.offer_type %}{% trans "предложение партнёра" %}{% else %}{% trans "спрос партнёра" %}{% endif %}</div>
            {% endif %}
        {% endif %}
        <div class="right"></div>
     </div>
         {% endif %}
     {% endif %}
     <div class="clearfix"></div>
</div>

templates/market/offer_form.html
{% extends "base.html" %}
{% load i18n %}
{% load seo %}
{% load deal_patterns %}
{% block title %}{{ submit_title }}{% endblock %}
{% block metatags %}{% get_metadata %}{% endblock %}
{% block extrahead %}
<script type="text/javascript">
    $(document).ready(function() {

        var id_region_placeholder = $('#cuselFrame-id_region .cuselText').html();

        if ($('#id_country').val() != 3159) {
            $('div.region').hide();
        };

        $('#id_location_0').djselectable('option', 'prepareQuery', add_country);

        $('#id_country').live('change', function(){
            if ($(this).val() == 3159){
                $('.region').show();
            }else{
                $('.region').hide();
            }
            $('#id_location_0').val('');
            $('#id_location_1').val('');
            $('#id_region').val('');
            $('#cuselFrame-id_region .cuselText').html(id_region_placeholder);
        });

        $('#id_region').live('change', function(){
            $('#id_location_0').val('');
            $('#id_location_1').val('');
        });
    });
</script>
<script type="text/javascript" src="/static/market/js/market.js"></script>
<link rel="stylesheet" type="text/css" href="/static/market/css/market.css">
{% endblock %}
{% block content %}
    <script>
        $(function() {
            $( ".datepicker" ).datepicker({dateFormat:'dd.mm.yy'});
        });
    </script>
    <form action="" enctype="multipart/form-data" method="post" id="offer_form">
        {% csrf_token %}
        <div class="block_border none_border">
            <div class="title_blue">
                <h1 class="inner">{% trans 'Маркет' %}</h1>
            </div>
	</div>
        <div class="block_border">
            <div class="one_columns">
                <div class="one_column1">
                    <h2>{% trans "Тип объявления" %}:</h2>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{% trans "Выберите тип" %}:</div></div>
                        <div>
                            {% if form.instance.pk %}
                               {% for choice in form.offer_type %}
                                   {% if choice.choice_value|slugify == form.instance.offer_type|slugify %}
                                       <span class="parent_input radio">
                                           <label for="offer_type_{{ forloop.counter0 }}" class="check">
                                               {{ choice.choice_label }}
                                           </label>
                                           {{ choice.tag }}
                                       </span>
                                   {% endif %}
                               {% endfor %}
                            {% else %}
                            <span class="parent_input radio">
                              <label for="offer_type_0" {% if form.offer_type.value|slugify == '1' %}class="check"{% endif %} onclick="window.location='{% url market:offer_create %}'">
                                  {{ form.offer_type.0.choice_label }}
                              </label>
                              {{ form.offer_type.0.tag }}
                            </span>
                            <span class="parent_input radio">
                              <label for="offer_type_1" {% if form.offer_type.value|slugify == '0' %}class="check"{% endif %} onclick="window.location='{% url market:demand_create %}'">
                                  {{ form.offer_type.1.choice_label }}
                              </label>
                              {{ form.offer_type.1.tag }}
                            </span>
                            {% endif %}
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="line_gray"></div>
            <div class="one_columns">
                <div class="one_column1">
                    <h2>{% trans "Товар" %}</h2>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.goods.label }}:</div></div>
                        <div class="left">{{ form.goods }}</div>
                        <div class="title"><div class="inner spec"><span class="required">*</span></div></div>
                        {% if form.goods.errors %} <div class="error">{{form.goods.errors.as_text }}</div> {% endif %}
                        <div class="clear"></div>
                    </div>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.grade.label }}:</div></div>
                        <div class="left">{{ form.grade }}</div>
                        <div class="clear"></div>
                    </div>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.caliber_min.label }}:</div></div>
                        <div class="left">{{ form.caliber_min }}</div>
                        <div class="title"><div class="inner spec"><span>&#8212;</span></div></div>
                        <div class="left">{{ form.caliber_max }}</div>
                        <div class="clear"></div>
                    </div>
                    {% if form.manufacturer.label %}
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.manufacturer.label }}:</div></div>
                        <div class="left">{{ form.manufacturer }}</div>
                        <div class="clear"></div>
                    </div>
                    {% endif %}
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.origin_country.label }}:</div></div>
                        <div class="left">{{ form.origin_country }}</div>
                        <div class="title"><div class="inner spec"><span class="required">*</span></div></div>
                        {% if form.origin_country.errors %} 
                        <div class="wide error">{{form.origin_country.errors.as_text }}</div> 
                        {% endif %}
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="line_gray"></div>
            <div class="one_columns">
                <div class="one_column1">
                    <h2>{% trans "География" %}</h2>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.pack.label }}:</div></div>
                        <div class="left">{{ form.pack }}</div>
                        <div class="clear"></div>
                    </div>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.country.label }}:</div></div>
                        <div class="left">{{ form.country }}</div>
                        <div class="title"><div class="inner spec"><span class="required">*</span></div></div>
                        {% if form.country.errors %} <div class="error">{{form.country.errors.as_text }}</div> {% endif %}
                        <div class="clear"></div>
                    </div>
                    <div class="wrapper_line region">
                        <div class="title wide"><div class="inner">&nbsp;</div></div>
                        <div class="left">{{ form.region }}</div>
                        <div class="title"><div class="inner spec"><span class="required">*</span></div></div>
                        {% if form.region.errors %} <div class="error">{{form.region.errors.as_text }}</div> {% endif %}
                        <div class="clear"></div>
                    </div>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">&nbsp;</div></div>
                        <div class="left">{{ form.location }}</div>
                        <div class="title"><div class="inner spec"><span class="required">*</span></div></div>
                        {% if form.location.errors %} <div class="error">{{form.location.errors.as_text }}</div> {% endif %}
                        <div class="clear"></div>
                    </div>
                    {% if form.delivery %}
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.delivery.label }}:</div></div>
                        <div class="left parent_input"><div class="inner">{{ form.delivery }} <label for="id_delivery" {% if form.instance.delivery %}class="check"{% endif %}></label></div></div>
                        <div class="clear"></div>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="line_gray"></div>
            <div class="one_columns">
                <div class="one_column1">
                    <h2>{% trans "Стоимость" %}</h2>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner" id="price_title">{{ form.price.label }}:</div></div>
                        <div class="left">{{ form.price }}</div>
                        <div class="title"><div class="inner spec"><span class="required">*</span></div></div>
                        <div class="title wide2"><div class="inner">{{ form.money_type.label }}:</div></div>
                        <div class="left">{{ form.money_type }} </div>
                        <div class="title"><div class="inner spec"><span class="required">*</span></div></div>
                        {% if form.money_type.errors %} <div class="error">{{form.money_type.errors.as_text }}</div> {% endif %}
                        {% if form.price.errors %} <div class="error">{{form.price.errors.as_text }}</div> {% endif %}
                        <div class="clear"></div>
                    </div>
                    <div class="wrapper_line">
                        <div style="display:none;">{{ form.payment_type }}</div>
                        <div class="title wide"><div class="inner">{{ form.payment_type.label }}:</div></div>
                        <div class="left cb_horizontal parent_input">
                            {{ form.payment_type }}
                        </div>
                        {% if form.payment_type.errors %} <div class="error">{{form.payment_type.errors.as_text }}</div> {% endif %}
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="line_gray"></div>
            <div class="one_columns">
                <div class="one_column1">
                    <h2>{% trans "Дополнительно" %}</h2>
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{{ form.notes.label }}:</div></div>
                        <div class="left">{{ form.notes }}</div>
                        {% if form.notes.errors %} <div class="error">{{form.notes.errors.as_text }}</div> {% endif %}
                        <div class="clear"></div>
                    </div>
                </div>
            </div> 
            <div class="line_gray"></div>
            <div class="one_columns">
                <div class="one_column1">
                    <h2>{% trans "Медиа" %}</h2>
                    {{ photo_inline.management_form }}
                    {% for img in photo_inline %}
                    <div class="wrapper_line">
                        <div class="title wide"><div class="inner">{% if forloop.counter0 %}&nbsp;{% else %}{% trans "Фотографии" %}:{% endif %}</div></div>
                        <div class="left imageline">{% if img.instance.img %}<img class="smallimage" src="{{ img.instance.img.url }}" />{% endif %}{{ img }}</div>
                        <div class="clear"></div>      
                    </div>
                    {% endfor %}
                </div>
            </div> 
            <br />
            <div class="gray_block">
                <div class="left_column2">
                    <a href="#" class="button green" id="submit_button" onclick="$('#offer_form').submit()">
                        <span>{{ submit_title }}</span>
                    </a>
                </div>
                <div class="left_column3">
                    <a href="{% if request.META.HTTP_REFERER %}{{ request.META.HTTP_REFERER }}{% else %}{{ cancel_url }}{% endif %}" class="button"><span>{{ cancel_title }}</span></a>
                </div>
                <div class="right_column2">
                {% if form.instance.date_create|days_ago > 0 %}
                    <a href="{% url market:renew form.instance.pk %}" class="button fr"><span>{% trans "Обновить" %}</span></a>
                {% endif %}
                </div>
            </div>
        </div>
    </form>
{% endblock %}